apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: mindclade-platform
    gitops.mindclade.io/activation: inactive
configMapGenerator:
  - name: external-secrets-release-contract
    files: [release.yaml, values.yaml]
