version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
    open-pull-requests-limit: 5
    labels: [dependencies, github-actions]
    reviewers:
      - mindclade/platform-operations
      - mindclade/security
  - package-ecosystem: gomod
    directory: /tooling
    schedule:
      interval: weekly
    groups:
      tooling-runtime:
        patterns: ["*"]
    open-pull-requests-limit: 5
    labels: [dependencies, go]
    reviewers:
      - mindclade/platform-operations
      - mindclade/security
  - package-ecosystem: bazel
    directory: /
    schedule:
      interval: weekly
    groups:
      bazel-modules:
        patterns: ["*"]
    open-pull-requests-limit: 5
    labels: [dependencies, bazel]
    reviewers:
      - mindclade/platform-operations
      - mindclade/security
