apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "false"
  users.anonymous.enabled: "false"
  exec.enabled: "false"
  statusbadge.enabled: "false"
  application.resourceTrackingMethod: annotation+label
  resource.respectRBAC: strict
  resource.customizations.ignoreDifferences.all: |
    jqPathExpressions:
      - .metadata.managedFields
